version: "3"

services:
  flipt:
    image: markphelps/flipt:latest
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - backend
    volumes:
      - ".:/var/opt/flipt"

  example:
    build: .
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - flipt

networks:
  backend:
